export const users = [
  {
    id: "123e4567-e89b-12d3-a456-426614174000",
    user_name: "namusste",
    bio: "Avid surfer",
    img: "",
    following_count: 1,
    followers_count: 1,
    first_name: "Connor",
    last_name: "Musson",
    email: "connor@gmail.com",
    password: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "18c1237f-363e-44db-9999-5adc3afd279c",
    user_name: "adrianito",
    bio: "Living the mustache life",
    img: "",
    following_count: 1,
    followers_count: 1,
    first_name: "Adriano",
    last_name: "Gonzalez",
    email: "adri@gmail.com",
    password: "4567",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b28f24a1-77ec-4809-a26e-ee35068d12a8",
    user_name: "albanito",
    bio: "Looking for a jam",
    img: "",
    following_count: 0,
    followers_count: 0,
    first_name: "Alban",
    last_name: "Mansord",
    email: "albanmsd@gmail.com",
    password: "7890",
    createdAt: new Date(),
    updatedAt: new Date(),
  }, 
]

// export default users;